nameOverride: "growweek-backend-dev"
fullnameOverride: "growweek-backend-dev"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: dev.growweek.robinjoon.xyz
      paths:
        - path: /api/
          pathType: Prefix
  tls:
    - secretName: growweek-backend-dev-tls
      hosts:
        - dev.growweek.robinjoon.xyz

image:
  repository: "harbor.homelab.robinjoon.xyz/growweek/backend"
  tag: "20251226"

imagePullSecrets:
  - name: "growweek-harbor-secret"